export const Images = {
    avatarDF: require('./ICON_JUPVIEC/avatardf.png'),
    banner1: require('./ICON_JUPVIEC/banner1.png'),
    banner2: require('./ICON_JUPVIEC/banner2.png'),
    banner3: require('./ICON_JUPVIEC/banner3.png'),
    banner4: require('./ICON_JUPVIEC/banner4.png'),
    banner5: require('./ICON_JUPVIEC/banner5.png'),
    banner6: require('./ICON_JUPVIEC/banner6.png'),
    ic1: require('./ICON_JUPVIEC/ic1.png'),
    ic2: require('./ICON_JUPVIEC/ic2.png'),
    ic3: require('./ICON_JUPVIEC/ic3.png'),
    ic4: require('./ICON_JUPVIEC/ic4.png'),
    ic5: require('./ICON_JUPVIEC/ic5.png'),
    ic6: require('./ICON_JUPVIEC/ic6.png'),
    ic7: require('./ICON_JUPVIEC/ic7.png'),
    icMessenger: require('./ICON_JUPVIEC/messenger.png'),
    icVi: require('./ICON_JUPVIEC/wallet.png'),
    BGHome: require('./ICON_JUPVIEC/bghome.png'),
    icHeart: require('./ICON_JUPVIEC/heart.png'),
    icHandshake: require('./ICON_JUPVIEC/handshake.png'),
    icLocation: require('./ICON_JUPVIEC/location.png'),
    icTelephoneCall: require('./ICON_JUPVIEC/telephone-call.png'),
    icLogout: require('./ICON_JUPVIEC/logout.png'),
    icSetting: require('./ICON_JUPVIEC/setting.png'),
    icBack: require('./ICON_JUPVIEC/back.png'),
    icBrokenHeart: require('./ICON_JUPVIEC/brokenheart.png'),
    icChat: require('./ICON_JUPVIEC/chatwith.png'),
    icEmail: require('./ICON_JUPVIEC/email.png'),
    icNotes: require('./ICON_JUPVIEC/notes.png'),
    icQRScan: require('./ICON_JUPVIEC/qrscan.png'),
    icLogoApp: require('./ICON_JUPVIEC/logoApp.png'),
    icView: require('./ICON_JUPVIEC/view.png'),
    icHidden: require('./ICON_JUPVIEC/hidden.png'),

    // icon cũ
    icDatDV: require('./ICON_JUPVIEC/datdv.png'),
    icHoatDong: require('./ICON_JUPVIEC/hdong.png'),
    icKhac: require('./ICON_JUPVIEC/khac.png'),
    icLichSu: require('./ICON_JUPVIEC/lichsu.png'),
    icLogo1: require('./ICON_JUPVIEC/logo1.jpg'),
    icMaQR: require('./ICON_JUPVIEC/maqr.png'),
    icProfile: require('./ICON_JUPVIEC/profile.jpg'),
    icSOS: require('./ICON_JUPVIEC/sos.jpg'),
    icThongBao: require('./ICON_JUPVIEC/tb.png'),
    icTaiKhoan: require('./ICON_JUPVIEC/tk.jpg'),

}