platform :ios, '11.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'SourceCore' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  pod 'Permission-SpeechRecognition', :path => "#{permissions_path}/SpeechRecognition.podspec"

  rn_maps_path = '../node_modules/react-native-maps'
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'GoogleSignIn', '~> 5.0.1'
  
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'

  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  
  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'
  pod 'react-native-blur', :path => '../node_modules/@react-native-community/blur'
  pod 'react-native-restart', :path => '../node_modules/react-native-restart'
  pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
  'FaceDetectorMLKit'
  ]

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'OneSignalNotificationServiceExtension' do
      pod 'OneSignal', '>= 2.9.3', '< 3.0'
  end
  # pod 'SwiftWebSocket'
  pod 'SwiftWebSocket', :git => 'https://github.com/tidwall/SwiftWebSocket.git', :tag => 'v2.8.0'

  target 'SourceCoreTests' do
    inherit! :complete
    #inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
  # use_flipper!({ 'Flipper' => '0.80.0' })
end

use_flipper!({ 'Flipper' => '0.87.0', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1' })
post_install do |installer|
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  react_native_post_install(installer)

  # Fix for Upgrade RN 0.64
  find_and_replace("Pods/RCT-Folly/folly/synchronization/DistributedMutex-inl.h",
        "  atomic_notify_one(state);", "  folly::atomic_notify_one(state);")

  # Fix lỗi import ReactNativeBlobUtil from 'react-native-blob-util'
  find_and_replace("../node_modules/react-native-pdf/index.js",
  "import ReactNativeBlobUtil from 'react-native-blob-util'", "import ReactNativeBlobUtil from 'rn-fetch-blob'")

  # Fix for XCode 12.5
  find_and_replace("../node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm",
  "_initializeModules:(NSArray<id<RCTBridgeModule>> *)modules", "_initializeModules:(NSArray<Class> *)modules")
  find_and_replace("../node_modules/react-native/ReactCommon/turbomodule/core/platform/ios/RCTTurboModuleManager.mm",
  "RCTBridgeModuleNameForClass(strongModule))", "RCTBridgeModuleNameForClass(Class(strongModule)))")

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
    end
  end
end


target 'SourceCore-tvOS' do
 # Pods for SourceCore-tvOS

 target 'SourceCore-tvOSTests' do
   inherit! :search_paths
   # Pods for testing
 end

end
def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)

      if text != replace
          puts "Fix: " + name
          system("chmod +w " + name)
          File.open(name, "w") { |file| file.puts replace }
          STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end
